{{- if and .Values.agentToken (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warpgrid-agent.fullname" . }}
  labels:
    {{- include "warpgrid-agent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.agentToken | b64enc | quote }}
{{- end }}
