#!/usr/bin/env bash
#
# build-libpq.sh — Cross-compile PostgreSQL's libpq to wasm32-wasip2.
#
# Produces a static libpq.a and headers under build/libpq-wasm/ that can
# be linked with C programs compiled against the patched wasi-libc sysroot.
#
# libpq compiled WITHOUT TLS support — the WarpGrid database proxy handles
# TLS transparently on the host side. This eliminates the OpenSSL dependency.
#
# Prerequisites:
#   - Patched wasi-libc sysroot (run scripts/build-libc.sh --patched first)
#   - wasi-sdk (auto-detected from build cache)
#   - git
#
# Usage:
#   scripts/build-libpq.sh                 # Build libpq for wasm32-wasip2
#   scripts/build-libpq.sh --clean         # Clean and rebuild
#   scripts/build-libpq.sh --help          # Show this help
#
# Environment variables:
#   WASI_SDK_PATH    Path to wasi-sdk (uses build cache if unset)
#   PG_VERSION       PostgreSQL release tag (default: REL_16_2)
#   TARGET_TRIPLE    WASI target triple (default: wasm32-wasip2)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BUILD_DIR="${PROJECT_ROOT}/build"
CACHE_DIR="${BUILD_DIR}/cache"
LIBPQ_BUILD_DIR="${BUILD_DIR}/libpq-build"
LIBPQ_INSTALL_DIR="${BUILD_DIR}/libpq-wasm"
PG_SOURCE_DIR="${BUILD_DIR}/postgresql-src"

PG_VERSION="${PG_VERSION:-REL_16_2}"
TARGET_TRIPLE="${TARGET_TRIPLE:-wasm32-wasip2}"

# ─── Helpers ─────────────────────────────────────────────────────────────────

log() { echo "==> $*" >&2; }
err() { echo "ERROR: $*" >&2; exit 1; }

usage() {
    echo "Usage: scripts/build-libpq.sh [--clean|--help]"
    echo
    echo "Cross-compile PostgreSQL's libpq to ${TARGET_TRIPLE}."
    echo
    echo "Flags:"
    echo "  --clean    Remove previous build artifacts and start fresh"
    echo "  --help     Show this help message"
    echo
    echo "Environment:"
    echo "  WASI_SDK_PATH    Path to wasi-sdk"
    echo "  PG_VERSION       PostgreSQL release tag (default: ${PG_VERSION})"
    echo "  TARGET_TRIPLE    Target triple (default: ${TARGET_TRIPLE})"
}

ensure_wasi_sdk() {
    if [[ -n "${WASI_SDK_PATH:-}" ]] && [[ -x "${WASI_SDK_PATH}/bin/clang" ]]; then
        return
    fi
    local cached
    cached=$(ls -d "${CACHE_DIR}/wasi-sdk-"* 2>/dev/null | head -1)
    if [[ -n "${cached}" && -x "${cached}/bin/clang" ]]; then
        WASI_SDK_PATH="${cached}"
        return
    fi
    err "wasi-sdk not found. Set WASI_SDK_PATH or run 'scripts/build-libc.sh --stock' first."
}

ensure_sysroot() {
    local sysroot="${BUILD_DIR}/sysroot-patched"
    if [[ ! -f "${sysroot}/lib/${TARGET_TRIPLE}/libc.a" ]]; then
        err "Patched sysroot not found. Run 'scripts/build-libc.sh --patched' first."
    fi
    SYSROOT="${sysroot}"
}

# ─── PostgreSQL source ───────────────────────────────────────────────────────

clone_postgresql() {
    if [[ -d "${PG_SOURCE_DIR}/.git" ]]; then
        local current_tag
        current_tag=$(cd "${PG_SOURCE_DIR}" && git describe --tags --exact-match 2>/dev/null || echo "")
        if [[ "${current_tag}" == "${PG_VERSION}" ]]; then
            log "PostgreSQL source at ${PG_VERSION} already cloned"
            return
        fi
        log "Cleaning stale PostgreSQL source..."
        rm -rf "${PG_SOURCE_DIR}"
    fi

    log "Cloning PostgreSQL ${PG_VERSION}..."
    git clone --depth 1 --branch "${PG_VERSION}" \
        https://github.com/postgres/postgres.git "${PG_SOURCE_DIR}"
}

# ─── WASI compatibility shims ────────────────────────────────────────────────

# libpq uses some POSIX functions not available in WASI. We provide minimal
# stubs to satisfy the linker. These are only needed for compilation —
# at runtime, the WarpGrid proxy handles all the networking transparently.

create_compat_shims() {
    local shim_dir="${LIBPQ_BUILD_DIR}/wasi-compat"
    mkdir -p "${shim_dir}"

    # pg_config_paths.h — normally generated by configure
    cat > "${shim_dir}/pg_config_paths.h" << 'HEREDOC'
/* Minimal pg_config_paths.h for WASI cross-compilation */
#define PGBINDIR "/usr/local/pgsql/bin"
#define PGSHAREDIR "/usr/local/pgsql/share"
#define SYSCONFDIR "/usr/local/pgsql/etc"
#define INCLUDEDIR "/usr/local/pgsql/include"
#define PKGINCLUDEDIR "/usr/local/pgsql/include"
#define INCLUDEDIRSERVER "/usr/local/pgsql/include/server"
#define LIBDIR "/usr/local/pgsql/lib"
#define PKGLIBDIR "/usr/local/pgsql/lib"
#define LOCALEDIR "/usr/local/pgsql/share/locale"
#define DOCDIR "/usr/local/pgsql/doc"
#define HTMLDIR "/usr/local/pgsql/doc"
#define MANDIR "/usr/local/pgsql/man"
HEREDOC

    # pg_config.h — normally generated by configure
    cat > "${shim_dir}/pg_config.h" << 'HEREDOC'
/* Minimal pg_config.h for WASI cross-compilation */
#ifndef PG_CONFIG_H
#define PG_CONFIG_H

/* Version info */
#define PG_MAJORVERSION "16"
#define PG_MINORVERSION "2"
#define PG_VERSION "16.2"
#define PG_VERSION_NUM 160002
#define PG_VERSION_STR "PostgreSQL 16.2 (WarpGrid WASI build)"

/* Platform configuration */
#define BLCKSZ 8192
#define XLOG_BLCKSZ 8192
#define MAXIMUM_ALIGNOF 8
#define FLOAT8PASSBYVAL true

/* Endianness */
#ifndef WORDS_BIGENDIAN
/* wasm32 is little-endian */
#endif

/* Types */
#define SIZEOF_LONG 4
#define SIZEOF_SIZE_T 4
#define SIZEOF_VOID_P 4
#define PG_INT64_TYPE long long
#define HAVE_LONG_LONG_INT 1
#define HAVE_LONG_LONG_INT_64 1
/* Don't define HAVE_INT64 — let c.h provide the typedef */
#define PG_PRINTF_ATTRIBUTE gnu_printf

/* Features we HAVE */
#define HAVE_STDINT_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_MEMORY_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_ERRNO_H 1
#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_STRLCPY 1
#define HAVE_STRLCAT 1
#define HAVE_STRTOLL 1
#define HAVE_STRTOULL 1
#define HAVE_STRERROR 1
#define HAVE_RINT 1
#define HAVE_FSEEKO 1
#define HAVE_DECL_STRLCPY 1
#define HAVE_DECL_STRLCAT 1
#define HAVE_DECL_SNPRINTF 1
#define HAVE_DECL_VSNPRINTF 1
#define HAVE_FUNCNAME__FUNC 1
#define HAVE_GETADDRINFO 1

/* Features we DO NOT HAVE on WASI */
/* #undef HAVE_SYS_UN_H */
/* #undef HAVE_POLL_H */
/* #undef HAVE_SYS_POLL_H */
/* #undef HAVE_SYS_SELECT_H */
/* #undef HAVE_SYS_EPOLL_H */
/* #undef HAVE_PTHREAD_H */
/* #undef HAVE_DLFCN_H */
/* #undef USE_OPENSSL */
/* #undef USE_LDAP */
/* #undef ENABLE_GSS */
/* #undef ENABLE_SSPI */
/* #undef HAVE_UNIX_SOCKETS */
/* #undef HAVE_SYS_UIO_H */
/* #undef HAVE_WRITEV */
/* #undef HAVE_POLL */
/* #undef HAVE_PREAD */
/* #undef HAVE_PWRITE */
/* #undef HAVE_READV */
/* #undef HAVE_SETSOCKOPT */
/* #undef HAVE_GETSOCKOPT */
/* #undef HAVE_GETTIMEOFDAY */
/* #undef HAVE_SIGNAL_H */
/* #undef HAVE_SIGPROCMASK */
/* #undef HAVE_DLOPEN */
/* #undef HAVE_FCNTL_H */

/* Disable SSL */
/* #undef USE_SSL */

/* Misc */
/* NLS disabled — no libintl.h on WASI */
/* #undef ENABLE_NLS */
#define INT64_MODIFIER "ll"
#define PGDLLIMPORT
#define PGDLLEXPORT
#define pg_attribute_noreturn() __attribute__((noreturn))
#define pg_attribute_printf(a,b) __attribute__((format(printf,a,b)))
#define pg_attribute_unused() __attribute__((unused))

/* Defaults used by fe-connect.c */
#define DEF_PGPORT 5432
#define DEF_PGPORT_STR "5432"
#define PG_KRB_SRVNAM "postgres"

/* MemSet optimization threshold — used by c.h's MemSet macro */
#define MEMSET_LOOP_LIMIT 1024

/* EHOSTDOWN is not defined in WASI — map to EHOSTUNREACH */
#ifndef EHOSTDOWN
#define EHOSTDOWN 112
#endif

/* pg_restrict — C99 restrict keyword support (normally set by configure) */
#define pg_restrict __restrict

/* geteuid — not in WASI headers, declared in our compat shim */
unsigned int geteuid(void);

/* Standard POSIX types */
typedef unsigned int socklen_t;

#endif /* PG_CONFIG_H */
HEREDOC

    # pg_config_os.h — empty, not needed for WASI
    cat > "${shim_dir}/pg_config_os.h" << 'HEREDOC'
/* Empty pg_config_os.h for WASI */
#ifndef PG_CONFIG_OS_H
#define PG_CONFIG_OS_H
#endif
HEREDOC

    # Stub for functions not available in WASI
    cat > "${shim_dir}/wasi_compat.c" << 'HEREDOC'
/* WASI compatibility stubs for libpq.
 * These satisfy linker requirements for functions not available in WASI.
 * The WarpGrid proxy handles all networking transparently, so most of
 * these are never called at runtime.
 *
 * All stubs use __attribute__((weak)) so they yield to any strong
 * definition provided by the WASI sysroot or the linking program. */

#include <errno.h>
#include <string.h>
#include <stdlib.h>

#define WEAK __attribute__((weak))

/* fcntl — used by libpq for setting socket non-blocking. */
WEAK int fcntl(int fd, int cmd, ...) {
    (void)fd; (void)cmd;
    return 0;
}

/* getsockname — used by libpq to get local socket address after connect.
 * Return a fake IPv4 loopback address. */
#include <sys/socket.h>
#include <netinet/in.h>
WEAK int getsockname(int fd, struct sockaddr *addr, socklen_t *addrlen) {
    (void)fd;
    if (addr && addrlen && *addrlen >= sizeof(struct sockaddr_in)) {
        struct sockaddr_in *sin = (struct sockaddr_in *)addr;
        sin->sin_family = 2; /* AF_INET */
        sin->sin_port = 0;
        sin->sin_addr.s_addr = 0x0100007F; /* 127.0.0.1 in network order */
        *addrlen = sizeof(struct sockaddr_in);
    }
    return 0;
}

/* getpeername — used by libpq to get peer socket address. */
WEAK int getpeername(int fd, struct sockaddr *addr, socklen_t *addrlen) {
    (void)fd;
    if (addr && addrlen && *addrlen >= sizeof(struct sockaddr_in)) {
        struct sockaddr_in *sin = (struct sockaddr_in *)addr;
        sin->sin_family = 2; /* AF_INET */
        sin->sin_port = 0x6e14; /* 5230 in network order — arbitrary */
        sin->sin_addr.s_addr = 0x0100007F; /* 127.0.0.1 */
        *addrlen = sizeof(struct sockaddr_in);
    }
    return 0;
}

/* setsockopt — used by libpq for TCP keepalive, nodelay, etc. */
WEAK int setsockopt(int fd, int level, int optname, const void *optval,
                    unsigned int optlen) {
    (void)fd; (void)level; (void)optname; (void)optval; (void)optlen;
    return 0;
}

/* getsockopt — used by libpq to check connection status. */
WEAK int getsockopt(int fd, int level, int optname, void *optval,
                    unsigned int *optlen) {
    (void)fd; (void)level; (void)optname;
    if (optval && optlen && *optlen >= sizeof(int)) {
        *(int *)optval = 0;
    }
    return 0;
}

/* select — used by libpq for connection timeout. */
WEAK int select(int nfds, void *readfds, void *writefds,
                void *exceptfds, void *timeout) {
    (void)nfds; (void)readfds; (void)writefds;
    (void)exceptfds; (void)timeout;
    return 1;
}

/* poll — used by libpq on some platforms. */
struct __libpq_pollfd { int fd; short events; short revents; };
WEAK int poll(struct __libpq_pollfd *fds, unsigned long nfds, int timeout) {
    (void)timeout;
    for (unsigned long i = 0; i < nfds; i++) {
        fds[i].revents = fds[i].events;
    }
    return (int)nfds;
}

/* gettimeofday — used by libpq for connection timing. */
struct __libpq_timeval { long tv_sec; long tv_usec; };
WEAK int gettimeofday(struct __libpq_timeval *tv, void *tz) {
    (void)tz;
    if (tv) { tv->tv_sec = 0; tv->tv_usec = 0; }
    return 0;
}

/* getpid — used by libpq for cancel key generation. */
WEAK int getpid(void) {
    return 1;
}

/* sigprocmask — not available in WASI. */
WEAK int sigprocmask(int how, const void *set, void *oldset) {
    (void)how; (void)set; (void)oldset;
    return 0;
}

/* geteuid — used by libpq for auth and home directory lookup. */
WEAK unsigned int geteuid(void) {
    return 0;
}

/* getpwuid — used by thread.c for username lookup. */
struct passwd { char *pw_name; char *pw_dir; };
static char fake_user[] = "wasi";
static char fake_home[] = "/";
static struct passwd fake_pw = { fake_user, fake_home };

WEAK struct passwd *getpwuid(unsigned int uid) {
    (void)uid;
    return &fake_pw;
}

WEAK int getpwuid_r(unsigned int uid, struct passwd *pwd, char *buf,
                    unsigned long buflen, struct passwd **result) {
    (void)uid; (void)buf; (void)buflen;
    if (pwd) *pwd = fake_pw;
    if (result) *result = &fake_pw;
    return 0;
}

/* popen/pclose — used by fe-print.c for pager output. */
#include <stdio.h>
WEAK FILE *popen(const char *command, const char *mode) {
    (void)command; (void)mode;
    return NULL;
}
WEAK int pclose(FILE *stream) {
    (void)stream;
    return -1;
}

/* pqsignal — used by fe-secure.c for signal handling.
 * WASI has limited signal support, just return SIG_DFL. */
typedef void (*pqsigfunc)(int);
WEAK pqsigfunc pqsignal(int signo, pqsigfunc func) {
    (void)signo; (void)func;
    return (pqsigfunc)0; /* SIG_DFL */
}

HEREDOC

    # sys/un.h shim — WASI's sockaddr_un lacks sun_path, libpq needs it for ip.c
    mkdir -p "${shim_dir}/sys"
    cat > "${shim_dir}/sys/un.h" << 'HEREDOC'
/* WASI compat sys/un.h — provides sun_path for PostgreSQL's ip.c */
#ifndef WASI_COMPAT_SYS_UN_H
#define WASI_COMPAT_SYS_UN_H

#include <sys/socket.h>

/* Redefine sockaddr_un with sun_path that PostgreSQL expects.
 * Unix sockets are not actually used — WarpGrid proxy handles connections. */
#ifdef sockaddr_un
#undef sockaddr_un
#endif
struct sockaddr_un {
    sa_family_t sun_family;
    char sun_path[108];
};

#endif /* WASI_COMPAT_SYS_UN_H */
HEREDOC

    # pwd.h stub — thread.c needs it for getpwuid_r
    cat > "${shim_dir}/pwd.h" << 'HEREDOC'
/* WASI compat pwd.h — stubs for user database functions */
#ifndef WASI_COMPAT_PWD_H
#define WASI_COMPAT_PWD_H

struct passwd {
    char *pw_name;
    char *pw_dir;
};

struct passwd *getpwuid(unsigned int uid);
int getpwuid_r(unsigned int uid, struct passwd *pwd, char *buf,
               unsigned long buflen, struct passwd **result);

#endif /* WASI_COMPAT_PWD_H */
HEREDOC

    # sys/termios.h stub — fe-print.c needs it for terminal output formatting
    cat > "${shim_dir}/sys/termios.h" << 'HEREDOC'
/* WASI compat sys/termios.h — stub for terminal I/O (not available in WASI) */
#ifndef WASI_COMPAT_SYS_TERMIOS_H
#define WASI_COMPAT_SYS_TERMIOS_H
/* Empty — terminal control not available in WASI */
#endif
HEREDOC

    # pg_config_ext.h — normally generated by configure, included from postgres_ext.h
    cat > "${shim_dir}/pg_config_ext.h" << 'HEREDOC'
/* Minimal pg_config_ext.h for WASI cross-compilation */
#ifndef PG_CONFIG_EXT_H
#define PG_CONFIG_EXT_H
#define PG_INT64_TYPE long long
#endif
HEREDOC

    # Also copy generated headers into the PG source include dir so that
    # quoted #include directives (which resolve relative to the source file)
    # find them before searching the -I paths.
    cp "${shim_dir}/pg_config.h" "${PG_SOURCE_DIR}/src/include/" 2>/dev/null || true
    cp "${shim_dir}/pg_config_ext.h" "${PG_SOURCE_DIR}/src/include/" 2>/dev/null || true
    cp "${shim_dir}/pg_config_os.h" "${PG_SOURCE_DIR}/src/include/port/" 2>/dev/null || true
    cp "${shim_dir}/pg_config_paths.h" "${PG_SOURCE_DIR}/src/include/" 2>/dev/null || true

    log "Created WASI compatibility shims in ${shim_dir}/"
}

# ─── Build libpq ─────────────────────────────────────────────────────────────

build_libpq() {
    local cc="${WASI_SDK_PATH}/bin/clang"
    local ar="${WASI_SDK_PATH}/bin/ar"

    local pg_src="${PG_SOURCE_DIR}/src"
    local shim_dir="${LIBPQ_BUILD_DIR}/wasi-compat"

    # Include paths
    local includes=(
        "-I${shim_dir}"
        "-I${pg_src}/include"
        "-I${pg_src}/interfaces/libpq"
        "-I${pg_src}/port"
        "-I${pg_src}/common"
    )

    local cflags=(
        "--target=${TARGET_TRIPLE}"
        "--sysroot=${SYSROOT}"
        "-O1"
        "-D__wasi__"
        "-DFRONTEND"
        "-D_WASI_EMULATED_SIGNAL"
        "-w"   # Suppress warnings for PostgreSQL source (not our code)
    )

    mkdir -p "${LIBPQ_BUILD_DIR}/obj"

    # libpq source files — core connection and query functionality
    local libpq_sources=(
        "${pg_src}/interfaces/libpq/fe-auth.c"
        "${pg_src}/interfaces/libpq/fe-connect.c"
        "${pg_src}/interfaces/libpq/fe-exec.c"
        "${pg_src}/interfaces/libpq/fe-lobj.c"
        "${pg_src}/interfaces/libpq/fe-misc.c"
        # fe-print.c excluded — provides legacy PQprint()/PQdisplayTuples(),
        # needs popen() which is not available in WASI. Not needed for proxy use.
        "${pg_src}/interfaces/libpq/fe-protocol3.c"
        "${pg_src}/interfaces/libpq/fe-secure.c"
        "${pg_src}/interfaces/libpq/fe-trace.c"
        "${pg_src}/interfaces/libpq/libpq-events.c"
        "${pg_src}/interfaces/libpq/fe-auth-scram.c"
        "${pg_src}/interfaces/libpq/pqexpbuffer.c"
    )

    # Required common/ source files
    local common_sources=(
        "${pg_src}/common/base64.c"
        "${pg_src}/common/cryptohash.c"
        "${pg_src}/common/encnames.c"
        "${pg_src}/common/hmac.c"
        "${pg_src}/common/ip.c"
        "${pg_src}/common/link-canary.c"
        "${pg_src}/common/md5.c"
        "${pg_src}/common/md5_common.c"
        "${pg_src}/common/pg_prng.c"
        "${pg_src}/common/scram-common.c"
        "${pg_src}/common/saslprep.c"
        "${pg_src}/common/sha1.c"
        "${pg_src}/common/sha2.c"
        "${pg_src}/common/string.c"
        "${pg_src}/common/stringinfo.c"
        "${pg_src}/common/unicode_norm.c"
        "${pg_src}/common/wchar.c"
    )

    # Required port/ source files
    local port_sources=(
        "${pg_src}/port/chklocale.c"
        "${pg_src}/port/getpeereid.c"
        "${pg_src}/port/inet_net_ntop.c"
        "${pg_src}/port/pg_bitutils.c"
        "${pg_src}/port/noblock.c"
        "${pg_src}/port/pg_strong_random.c"
        "${pg_src}/port/pgstrcasecmp.c"
        # pqsignal.c excluded — needs struct sigaction; stubbed in wasi_compat.c
        "${pg_src}/port/snprintf.c"
        "${pg_src}/port/strerror.c"
        "${pg_src}/port/thread.c"
    )

    # WASI compat shim
    local compat_sources=(
        "${shim_dir}/wasi_compat.c"
    )

    local all_sources=()
    all_sources+=("${libpq_sources[@]}")
    all_sources+=("${common_sources[@]}")
    all_sources+=("${port_sources[@]}")
    all_sources+=("${compat_sources[@]}")

    local compiled_objects=()
    local failed=0
    local compiled=0
    local skipped=0

    for src in "${all_sources[@]}"; do
        local basename
        basename="$(basename "${src}" .c)"
        local obj="${LIBPQ_BUILD_DIR}/obj/${basename}.o"

        if [[ ! -f "${src}" ]]; then
            log "SKIP: ${src} (file not found)"
            skipped=$((skipped + 1))
            continue
        fi

        if ! "${cc}" "${cflags[@]}" "${includes[@]}" -c -o "${obj}" "${src}" 2>"${LIBPQ_BUILD_DIR}/obj/${basename}.err"; then
            log "FAIL: ${src}"
            cat "${LIBPQ_BUILD_DIR}/obj/${basename}.err" | head -5
            failed=$((failed + 1))
            continue
        fi

        compiled_objects+=("${obj}")
        compiled=$((compiled + 1))
    done

    log "Compiled: ${compiled}  Failed: ${failed}  Skipped: ${skipped}"

    if [[ ${#compiled_objects[@]} -eq 0 ]]; then
        err "No objects compiled. Cannot create libpq.a"
    fi

    # Create static archive
    mkdir -p "${LIBPQ_INSTALL_DIR}/lib" "${LIBPQ_INSTALL_DIR}/include"

    "${ar}" rcs "${LIBPQ_INSTALL_DIR}/lib/libpq.a" "${compiled_objects[@]}"
    log "Created ${LIBPQ_INSTALL_DIR}/lib/libpq.a (${#compiled_objects[@]} objects)"

    # Copy headers
    cp "${pg_src}/interfaces/libpq/libpq-fe.h" "${LIBPQ_INSTALL_DIR}/include/"
    cp "${pg_src}/interfaces/libpq/libpq-events.h" "${LIBPQ_INSTALL_DIR}/include/"
    cp "${pg_src}/include/postgres_ext.h" "${LIBPQ_INSTALL_DIR}/include/"
    cp "${shim_dir}/pg_config.h" "${LIBPQ_INSTALL_DIR}/include/"
    cp "${shim_dir}/pg_config_ext.h" "${LIBPQ_INSTALL_DIR}/include/" 2>/dev/null || true

    # Create pg_config_ext.h if it doesn't exist
    if [[ ! -f "${LIBPQ_INSTALL_DIR}/include/pg_config_ext.h" ]]; then
        echo '#ifndef PG_CONFIG_EXT_H' > "${LIBPQ_INSTALL_DIR}/include/pg_config_ext.h"
        echo '#define PG_CONFIG_EXT_H' >> "${LIBPQ_INSTALL_DIR}/include/pg_config_ext.h"
        echo '#define PG_INT64_TYPE long long' >> "${LIBPQ_INSTALL_DIR}/include/pg_config_ext.h"
        echo '#endif' >> "${LIBPQ_INSTALL_DIR}/include/pg_config_ext.h"
    fi

    log "Installed headers to ${LIBPQ_INSTALL_DIR}/include/"

    if [[ ${failed} -gt 0 ]]; then
        log "WARNING: ${failed} source files failed to compile."
        log "libpq.a is partial — some features may be unavailable."
        return 1
    fi

    return 0
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    local clean=false

    while [[ $# -gt 0 ]]; do
        case "${1}" in
            --clean) clean=true ;;
            --help|-h) usage; exit 0 ;;
            *) err "Unknown flag: ${1}" ;;
        esac
        shift
    done

    ensure_wasi_sdk
    ensure_sysroot

    log "wasi-sdk:   ${WASI_SDK_PATH}"
    log "sysroot:    ${SYSROOT}"
    log "PG version: ${PG_VERSION}"

    if ${clean}; then
        log "Cleaning previous build..."
        rm -rf "${LIBPQ_BUILD_DIR}" "${LIBPQ_INSTALL_DIR}" "${PG_SOURCE_DIR}"
    fi

    clone_postgresql
    create_compat_shims
    build_libpq

    log "Done. libpq installation:"
    log "  Library: ${LIBPQ_INSTALL_DIR}/lib/libpq.a"
    log "  Headers: ${LIBPQ_INSTALL_DIR}/include/"
}

main "$@"
